name       : wxPython
version    : 3.0.2.0
release    : 4
source     :
    - http://internode.dl.sourceforge.net/project/wxpython/wxPython/3.0.2.0/wxPython-src-3.0.2.0.tar.bz2 : d54129e5fbea4fb8091c87b2980760b72c22a386cb3b9dd2eebc928ef5e8df61
license    :
    - WXwindows
    - LGPL-2.0
summary    : A blending of the wxWidgets C++ class library with the Python programming language.
description: |
    A blending of the wxWidgets C++ class library with the Python programming language.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libnotify)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(sdl2)
    - pkgconfig(sm)
    - pkgconfig(webkit2gtk-4.0)
    - libjpeg-turbo-devel
    - wxwidgets-devel
rundeps    :
    - wxwidgets
setup      : |
    %configure
build      : |
    cd wxPython
    python2 setup.py WXPORT=gtk2 UNICODE=1 build
install    : |
    cd wxPython
    python2 setup.py WXPORT=gtk2 UNICODE=1 install --root="$installdir"
