name       : wxPython
version    : 3.0.2.0
release    : 1
source     :
    - http://internode.dl.sourceforge.net/project/wxpython/wxPython/3.0.2.0/wxPython-src-3.0.2.0.tar.bz2 : d54129e5fbea4fb8091c87b2980760b72c22a386cb3b9dd2eebc928ef5e8df61
license    : 
    - WXwindows
    - LGPL-2.0
summary    : wxWidgets
description: |
    A blending of the wxWidgets C++ class library with the Python programming language.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libpng)
    - libjpeg-turbo-devel
    - pkgconfig(sm)
    - pkgconfig(libtiff-4)
    - pkgconfig(glu)
    - pkgconfig(libnotify)
    - pkgconfig(sdl2)
    - pkgconfig(webkit2gtk-4.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
